TEXTS = {
    "tr": {
        "sidebar_text": "Metin Eğitimi",
        "sidebar_image": "Görsel Eğitimi",
        "sidebar_audio": "Ses Eğitimi",
        "sidebar_tabular": "Tablo Eğitimi",
        "sidebar_inference": "Tahmin",
        "tab_config": "⚙️ Yapılandırma",
        "tab_results": "📊 Sonuçlar",
        "btn_file_select": "📂 Dosya Seç",
        "btn_folder_select": "📂 Klasör Seç",
        "lbl_no_file": "Dosya seçilmedi",
        "lbl_no_folder": "Klasör seçilmedi",
        "header_dataset": "📁 Veri Seti Seçimi",
        "header_models": "🤖 Model Seçimi",
        "header_params": "🎛️ Eğitim Parametreleri",
        "lbl_test_size": "Test Verisi Oranı:",
        "btn_start_training": "🚀 Eğitimi Başlat",
        "btn_training_running": "Eğitim Sürüyor...",
        "btn_clear_results": "🗑️ Sonuçları Temizle",
        "chk_optimize": "En İyi Parametreleri Bul (Grid Search)",
        "msg_training_complete": "Tüm eğitimler tamamlandı!\nSonuçlar ve veri setleri '{save_dir}' klasörüne kaydedildi.",
        "msg_error": "Hata",
        "msg_warning": "Uyarı",
        "msg_select_file_first": "Lütfen önce bir dosya seçin.",
        "msg_select_folder_first": "Lütfen önce veri setinin olduğu klasörü seçin.",
        "msg_select_features": "En az bir özellik sütunu seçmelisiniz.",
        "msg_select_target": "Bir hedef sütun seçmelisiniz.",
        "msg_select_model": "En az bir model seçmelisiniz.",
        "lbl_text_col": "Metin Sütunu:",
        "lbl_label_col": "Etiket Sütunu:",
        "lbl_max_features": "Max Kelime (Features):",
        "lbl_ngram": "N-Gram (Örn: 1,1):",
        "info_folder_structure": "ℹ️ Klasör içinde her sınıf için ayrı bir alt klasör olmalıdır.",
        "lbl_columns": "Sütun Ayarları",
        "col_feature": "Özellik (Girdi)",
        "col_name": "Sütun Adı",
        "col_text": "Metin Sütunu",
        "col_target": "Hedef (Çıktı)",
        "val_int_or_none": "(sayı veya 'None')",
        "btn_save": "Kaydet",
        "win_settings_title": "Ayarları",
        "lbl_params": "Parametreleri",
        "lang_toggle": "EN",
        "loading_data": "⏳ Veri yükleniyor...",
        "loading_images": "📂 Görseller yükleniyor...",
        "loading_audio": "🎵 Ses dosyaları işleniyor...",
        "err_no_images": "Klasörde uygun görsel bulunamadı!",
        "err_no_audio": "Klasörde uygun ses dosyası bulunamadı!",
        "col_select_first": "Önce Dosya Seçin",
        
        # Inference Tab
        "header_load": "📂 Model ve Veri Yükleme",
        "lbl_model_type": "Model Tipi:",
        "type_text": "Metin (Text)",
        "type_image": "Görüntü (Image)",
        "type_audio": "Ses (Audio)",
        "type_tabular": "Tablo (Tabular)",
        "btn_select_model": "Model Dosyası Seç (.joblib)",
        "btn_load_vectorizer": "Vectorizer Yükle",
        "btn_load_scaler": "Scaler Yükle",
        "btn_load_extra": "Diğer Dosyalar",
        "lbl_not_loaded": "Yüklü değil",
        "lbl_not_needed": "Gerekli değil",
        "lbl_loaded_auto": " (Otomatik)",
        "btn_load_features": "Sütun Bilgisi (feature_cols)",
        "btn_load_label_enc": "Label Encoder",
        "btn_load_encoder": "Preprocessor (encoder)",
        "header_predict": "🔮 Tahmin",
        "lbl_input_file": "Dosya seçilmedi",
        "lbl_tabular_input": "Veri Girişi",
        "btn_predict": "TAHMİN ET",
        "lbl_result_wait": "Sonuç bekleniyor...",
        "msg_model_loaded": "Model ve bulunan yardımcı dosyalar yüklendi.",
        "msg_file_loaded": "Dosya yüklendi.",
        "msg_enter_text": "Lütfen metin girin.",
        "msg_load_vectorizer": "Metin modelleri için Vectorizer yüklemelisiniz.",
        "msg_select_image": "Lütfen bir görüntü dosyası seçin.",
        "msg_select_audio": "Lütfen bir ses dosyası seçin.",
        "msg_load_features": "Lütfen sütun bilgisini (feature_cols) yükleyin.",
        "msg_load_model_first": "Lütfen önce bir model yükleyin.",

        # Parameter Descriptions
        "desc_alpha": "Düzeltme parametresi (0.0 - 1.0+)",
        "desc_var_smoothing": "Hesaplama kararlılığı için varyansın bir kısmı",
        "desc_C": "Düzenlileştirme katsayısı (Düşük=Daha Basit, Yüksek=Daha Karmaşık)",
        "desc_kernel": "Karar sınırının şekli",
        "desc_n_estimators": "Oluşturulacak ağaç sayısı",
        "desc_max_depth": "Ağacın maksimum derinliği (None=Sınırsız)",
        "desc_min_samples_split": "Bir düğümü bölmek için gereken min örnek sayısı",
        "desc_max_iter": "Maksimum iterasyon sayısı",
        "desc_learning_rate": "Her ağacın katkısını küçültme oranı (0.0-1.0)",
        "desc_n_neighbors": "Komşu sayısı (k)",
        "desc_weights": "Ağırlıklandırma (uniform=Eşit, distance=Uzaklığa göre)"
    },
    "en": {
        "sidebar_text": "Text Training",
        "sidebar_image": "Image Training",
        "sidebar_audio": "Audio Training",
        "sidebar_tabular": "Tabular Training",
        "sidebar_inference": "Inference",
        "tab_config": "⚙️ Configuration",
        "tab_results": "📊 Results",
        "btn_file_select": "📂 Select File",
        "btn_folder_select": "📂 Select Folder",
        "lbl_no_file": "No file selected",
        "lbl_no_folder": "No folder selected",
        "header_dataset": "📁 Dataset Selection",
        "header_models": "🤖 Model Selection",
        "header_params": "🎛️ Training Parameters",
        "lbl_test_size": "Test Data Ratio:",
        "btn_start_training": "🚀 Start Training",
        "btn_training_running": "Training...",
        "btn_clear_results": "🗑️ Clear Results",
        "chk_optimize": "Find Best Parameters (Grid Search)",
        "msg_training_complete": "All training completed!\nResults and datasets saved to '{save_dir}'.",
        "msg_error": "Error",
        "msg_warning": "Warning",
        "msg_select_file_first": "Please select a file first.",
        "msg_select_folder_first": "Please select the dataset folder first.",
        "msg_select_features": "You must select at least one feature column.",
        "msg_select_target": "You must select a target column.",
        "msg_select_model": "You must select at least one model.",
        "lbl_text_col": "Text Column:",
        "lbl_label_col": "Label Column:",
        "lbl_max_features": "Max Features:",
        "lbl_ngram": "N-Gram (e.g. 1,1):",
        "info_folder_structure": "ℹ️ There must be a separate subfolder for each class inside the folder.",
        "lbl_columns": "Column Settings",
        "col_feature": "Feature (Input)",
        "col_name": "Column Name",
        "col_text": "Text Column",
        "col_target": "Target (Output)",
        "val_int_or_none": "(number or 'None')",
        "btn_save": "Save",
        "win_settings_title": "Settings",
        "lbl_params": "Parameters",
        "lang_toggle": "TR",
        "loading_data": "⏳ Loading data...",
        "loading_images": "📂 Loading images...",
        "loading_audio": "🎵 Processing audio files...",
        "err_no_images": "No suitable images found in the folder!",
        "err_no_audio": "No suitable audio files found in the folder!",
        "col_select_first": "Select File First",

        # Inference Tab
        "header_load": "📂 Load Model & Data",
        "lbl_model_type": "Model Type:",
        "type_text": "Text",
        "type_image": "Image",
        "type_audio": "Audio",
        "type_tabular": "Tabular",
        "btn_select_model": "Select Model File (.joblib)",
        "btn_load_vectorizer": "Load Vectorizer",
        "btn_load_scaler": "Load Scaler",
        "btn_load_extra": "Other Files",
        "lbl_not_loaded": "Not loaded",
        "lbl_not_needed": "Not needed",
        "lbl_loaded_auto": " (Auto)",
        "btn_load_features": "Column Info (feature_cols)",
        "btn_load_label_enc": "Label Encoder",
        "btn_load_encoder": "Preprocessor (encoder)",
        "header_predict": "🔮 Predict",
        "lbl_input_file": "No file selected",
        "lbl_tabular_input": "Data Input",
        "btn_predict": "PREDICT",
        "lbl_result_wait": "Waiting for result...",
        "msg_model_loaded": "Model and auxiliary files loaded.",
        "msg_file_loaded": "File loaded.",
        "msg_enter_text": "Please enter text.",
        "msg_load_vectorizer": "You must load a Vectorizer for text models.",
        "msg_select_image": "Please select an image file.",
        "msg_select_audio": "Please select an audio file.",
        "msg_load_features": "Please load column info (feature_cols).",
        "msg_load_model_first": "Please load a model first.",

        # Parameter Descriptions
        "desc_alpha": "Smoothing parameter (0.0 - 1.0+)",
        "desc_var_smoothing": "Portion of variance for calculation stability",
        "desc_C": "Regularization parameter (Low=Simpler, High=More Complex)",
        "desc_kernel": "Shape of the decision boundary",
        "desc_n_estimators": "Number of trees to build",
        "desc_max_depth": "Maximum depth of the tree (None=Unlimited)",
        "desc_min_samples_split": "Min samples required to split a node",
        "desc_max_iter": "Maximum number of iterations",
        "desc_learning_rate": "Rate to shrink contribution of each tree (0.0-1.0)",
        "desc_n_neighbors": "Number of neighbors (k)",
        "desc_weights": "Weighting (uniform=Equal, distance=By Distance)"
    }
}

def get_text(key, lang="tr"):
    return TEXTS.get(lang, TEXTS["tr"]).get(key, key)
