TEXTS = {
    "tr": {
        "app_title": "Training Interface",
        "sidebar_text": "Metin Eğitimi",
        "sidebar_image": "Görsel Eğitimi",
        "sidebar_audio": "Ses Eğitimi",
        "sidebar_tabular": "Tablo Eğitimi",
        "sidebar_inference": "Tahmin",
        "tab_config": "⚙️ Yapılandırma",
        "tab_results": "📊 Sonuçlar",
        "btn_file_select": "📂 Dosya Seç",
        "btn_folder_select": "📂 Klasör Seç",
        "lbl_no_file": "Dosya seçilmedi",
        "lbl_no_folder": "Klasör seçilmedi",
        "header_dataset": "📁 Veri Seti Seçimi",
        "header_models": "🤖 Model Seçimi",
        "header_params": "🎛️ Eğitim Parametreleri",
        "lbl_test_size": "Test Verisi Oranı:",
        "btn_start_training": "🚀 Eğitimi Başlat",
        "btn_stop_training": "🛑 Eğitimi Durdur",
        "btn_stopping": "🛑 Durduruluyor...",
        "btn_training_running": "Eğitim Sürüyor...",
        "btn_clear_results": "🗑️ Sonuçları Temizle",
        "lbl_output_options": "📦 Çıktı Seçenekleri",
        "opt_save_models": "Model dosyaları",
        "opt_save_datasets": "Veri setleri",
        "opt_save_vectorizer": "Vectorizer",
        "opt_save_scaler": "Scaler",
        "opt_save_extra": "Ek dosyalar",
        "opt_save_plots": "Grafikler",
        "opt_save_comparison": "Karşılaştırma CSV",
        "opt_save_summary": "Özet raporlar (JSON/MD/HTML)",
        "opt_save_model_card": "Model kartı",
        "opt_save_onnx": "ONNX export",

        "help_stop_words": "Stop-words, metinlerde sık geçen ama anlam taşıma gücü düşük kelimeleri (ve, ile, the, and gibi) çıkarır. Metin sınıflandırmada gürültüyü azaltıp performansı artırabilir. Metin eğitimi ekranında Stop-words seçeneğinden Türkçe/İngilizce seçin.",
        "help_sparse_tfidf": "Seyrek TF-IDF, büyük metin setlerinde belleği azaltmak için sparse matris kullanır. Büyük veri setlerinde RAM kullanımını düşürür. Metin eğitimi ekranında 'Seyrek TF-IDF' kutusunu işaretleyin.",
        "help_low_memory_mode": "Düşük bellek modu, büyük görsel veri setlerinde dosyaları parça parça okuyarak RAM kullanımını düşürür. Görsel eğitim ekranında 'Düşük Bellek Modu' seçeneğini açın.",
        "help_augmentation": "Veri çoğaltma (augmentation), görüntülere dönüşüm uygulayarak veri setini büyütür ve genelleme performansını artırabilir. Görsel eğitim ekranında Veri Çoğaltma'yı açıp profil ve çarpan seçin.",
        "help_kfold": "K-Fold Cross-Validation, veriyi K parçaya bölüp birden fazla eğitim/test denemesi yapar. Küçük veri setlerinde daha güvenilir değerlendirme sağlar. K değerini 3 veya 5 gibi bir sayı yapıp etkinleştirin.",
        "help_output_options": "Çıktı seçenekleri ile hangi dosyaların kaydedileceğini seçebilirsiniz. Büyük çıktı klasörleri oluşmasını engellemek için gereksiz olanları kapatın.",

        "model_info_naive_bayes": "Naive Bayes; hızlı, basit ve özellikle metin sınıflandırmada güçlüdür. Özelliklerin bağımsız olduğunu varsayar. Büyük veri ve yüksek boyutlu metinlerde iyi çalışır.",
        "model_info_nb_gaussian": "Gaussian Naive Bayes; sürekli sayısal özellikler için uygundur. Basit, hızlı ve az veri ile çalışabilir.",
        "model_info_svm": "SVM; sınıfları en iyi ayıran hiper düzlemi bulur. Yüksek boyutlu veride güçlüdür. Küçük/orta ölçekli verilerde iyi sonuç verir.",
        "model_info_random_forest": "Random Forest; birden çok karar ağacının ortalamasını alır. Gürültüye dayanıklıdır, genellikle iyi bir başlangıç modelidir.",
        "model_info_log_reg": "Logistic Regression; hızlı ve yorumlanabilir bir doğrusal sınıflandırıcıdır. Metin ve tabular veride güçlü bir baseline sağlar.",
        "model_info_decision_tree": "Decision Tree; açıklanabilir ve hızlıdır. Aşırı öğrenmeye yatkındır; derinlik ayarları önemlidir.",
        "model_info_decision_tree_entropy": "Entropy kriterli Decision Tree; bilgi kazancına göre bölme yapar. Gini'ye alternatif olarak tercih edilebilir.",
        "model_info_gradient_boosting": "Gradient Boosting; hataları sıralı olarak düzelten güçlü bir ensemble yöntemidir. Daha uzun sürer ama yüksek doğruluk verir.",
        "model_info_knn": "KNN; en yakın komşulara göre karar verir. Basit ve eğitim maliyeti düşüktür, ancak büyük veri setlerinde yavaştır.",
        "model_info_linear_regression": "Linear Regression; hedefi doğrusal ilişki ile tahmin eder. Basit ve hızlı bir regresyon yöntemidir.",
        "model_info_ridge": "Ridge; doğrusal regresyona L2 regularizasyon ekler. Çoklu doğrusal bağlantı ve overfit sorunlarını azaltır.",
        "model_info_lasso": "Lasso; L1 regularizasyon ile bazı katsayıları sıfırlar, özellik seçimi yapabilir.",
        "model_info_svr": "SVR; SVM tabanlı regresyondur. Küçük/orta veri setlerinde güçlü performans sağlayabilir.",
        "model_info_rf_regressor": "Random Forest Regressor; güçlü ve esnek regresyon modeli. Gürültüye dayanıklıdır.",
        "model_info_gb_regressor": "Gradient Boosting Regressor; yüksek doğruluk potansiyeli sağlar fakat eğitim süresi uzundur.",
        "model_info_dt_regressor": "Decision Tree Regressor; açıklanabilir ama overfit olabilir. Derinlik ayarı önemlidir.",
        "model_info_knn_regressor": "KNN Regressor; komşuların ortalamasına göre tahmin yapar. Büyük veri setlerinde yavaştır.",
        "model_info_simple_cnn": "Simple CNN; küçük görüntü veri setleri için hızlı ve temel bir CNN mimarisi.",
        "model_info_deep_cnn": "Deep CNN; daha derin mimari, karmaşık görüntü setlerinde daha iyi sonuç verebilir fakat eğitim süresi uzundur.",
        "chk_optimize": "En İyi Parametreleri Bul (Grid Search)",
        "msg_training_started": "Eğitim başlatıldı...",
        "msg_training_complete": "Tüm eğitimler tamamlandı!\nSonuçlar ve veri setleri '{save_dir}' klasörüne kaydedildi.",
        "msg_error": "Hata",
        "msg_warning": "Uyarı",
        "msg_select_file_first": "Lütfen önce bir dosya seçin.",
        "msg_select_folder_first": "Lütfen önce veri setinin olduğu klasörü seçin.",
        "msg_select_features": "En az bir özellik sütunu seçmelisiniz.",
        "msg_select_target": "Bir hedef sütun seçmelisiniz.",
        "msg_select_model": "En az bir model seçmelisiniz.",
        "msg_file_read_error": "Dosya okunamadı: {error}",
        "msg_training_error": "Eğitim sırasında hata: {error}",
        "msg_model_load_error": "Model yüklenemedi: {error}",
        "msg_file_load_error": "Dosya yüklenemedi: {error}",
        "msg_load_error": "Yüklenemedi: {error}",
        "msg_audio_load_error": "Ses yükleme hatası: {error}",
        "msg_image_load_error": "Görsel yükleme hatası: {error}",
        "msg_batch_predict_error": "Batch tahmin hatası: {error}",
        "lbl_text_col": "Metin Sütunu:",
        "lbl_label_col": "Etiket Sütunu:",
        "lbl_max_features": "Max Kelime (Features):",
        "lbl_ngram": "N-Gram (Örn: 1,1):",
        "lbl_stop_words": "Stop-words:",
        "stop_words_none": "Yok",
        "stop_words_tr": "Türkçe",
        "stop_words_en": "İngilizce",
        "lbl_sparse_tfidf": "Seyrek TF-IDF (Düşük RAM)",
        "info_folder_structure": "ℹ️ Klasör içinde her sınıf için ayrı bir alt klasör olmalıdır.",
        "lbl_columns": "Sütun Ayarları",
        "col_feature": "Özellik (Girdi)",
        "col_name": "Sütun Adı",
        "col_text": "Metin Sütunu",
        "col_target": "Hedef (Çıktı)",
        "val_int_or_none": "(sayı veya 'None')",
        "btn_save": "Kaydet",
        "win_settings_title": "Ayarları",
        "lbl_params": "Parametreleri",
        "lbl_model_info_title": "{model} - Model Bilgisi",
        "lbl_accuracy": "Doğruluk (Accuracy)",
        "lbl_precision": "Hassasiyet (Precision)",
        "lbl_recall": "Duyarlılık (Recall)",
        "lbl_f1": "F1 Skoru",
        "lbl_r2": "R2",
        "lbl_mse": "MSE",
        "lbl_mae": "MAE",
        "lbl_model_comparison": "🏆 Genel Karşılaştırma",
        "lbl_best_model": "EN BAŞARILI MODEL",
        "lbl_model": "Model",
        "lbl_file": "Dosya",
        "lang_toggle": "EN",
        "loading_data": "⏳ Veri yükleniyor...",
        "loading_images": "📂 Görseller yükleniyor...",
        "loading_audio": "🎵 Ses dosyaları işleniyor...",
        "err_no_images": "Klasörde uygun görsel bulunamadı!",
        "err_no_audio": "Klasörde uygun ses dosyası bulunamadı!",
        "col_select_first": "Önce Dosya Seçin",
        
        # Inference Tab
        "header_load": "📂 Model ve Veri Yükleme",
        "lbl_model_type": "Model Tipi:",
        "type_text": "Metin (Text)",
        "type_image": "Görüntü (Image)",
        "type_audio": "Ses (Audio)",
        "type_tabular": "Tablo (Tabular)",
        "btn_select_model": "Model Dosyası Seç (.joblib)",
        "btn_load_vectorizer": "Vectorizer Yükle",
        "btn_load_scaler": "Scaler Yükle",
        "btn_load_extra": "Diğer Dosyalar",
        "lbl_not_loaded": "Yüklü değil",
        "lbl_not_needed": "Gerekli değil",
        "lbl_loaded_auto": " (Otomatik)",
        "lbl_scaler_optional": "Scaler (varsa)",
        "btn_load_features": "Sütun Bilgisi (feature_cols)",
        "btn_load_label_enc": "Label Encoder",
        "btn_load_encoder": "Preprocessor (encoder)",
        "header_predict": "🔮 Tahmin",
        "lbl_input_file": "Dosya seçilmedi",
        "lbl_tabular_input": "Veri Girişi",
        "btn_predict": "TAHMİN ET",
        "lbl_result_wait": "Sonuç bekleniyor...",
        "lbl_result": "Sonuç: {result}",
        "lbl_confidence": " (Güven: %{value})",
        "msg_model_loaded": "Model ve bulunan yardımcı dosyalar yüklendi.",
        "msg_file_loaded": "Dosya yüklendi.",
        "msg_enter_text": "Lütfen metin girin.",
        "msg_load_vectorizer": "Metin modelleri için Vectorizer yüklemelisiniz.",
        "msg_select_image": "Lütfen bir görüntü dosyası seçin.",
        "msg_select_audio": "Lütfen bir ses dosyası seçin.",
        "msg_load_features": "Lütfen sütun bilgisini (feature_cols) yükleyin.",
        "msg_load_model_first": "Lütfen önce bir model yükleyin.",
        "msg_encoding_error": "Encoding hatası: {error}\nGirdiğiniz değerler eğitim verisindeki kategorilerle eşleşmiyor olabilir.",

        # Parameter Descriptions
        "desc_alpha": "Düzeltme parametresi (0.0 - 1.0+)",
        "desc_var_smoothing": "Hesaplama kararlılığı için varyansın bir kısmı",
        "desc_C": "Düzenlileştirme katsayısı (Düşük=Daha Basit, Yüksek=Daha Karmaşık)",
        "desc_kernel": "Karar sınırının şekli",
        "desc_n_estimators": "Oluşturulacak ağaç sayısı",
        "desc_max_depth": "Ağacın maksimum derinliği (None=Sınırsız)",
        "desc_min_samples_split": "Bir düğümü bölmek için gereken min örnek sayısı",
        "desc_max_iter": "Maksimum iterasyon sayısı",
        "desc_learning_rate": "Her ağacın katkısını küçültme oranı (0.0-1.0)",
        "desc_n_neighbors": "Komşu sayısı (k)",
        "desc_weights": "Ağırlıklandırma (uniform=Eşit, distance=Uzaklığa göre)",
        
        # Yeni eklenen çeviriler
        "lbl_task_type": "Görev Tipi:",
        "task_classification": "Sınıflandırma",
        "task_regression": "Regresyon (Tahmin)",
        "lbl_grid_search_scope": "Grid Search Kapsamı:",
        "grid_search_all": "Tüm Modeller",
        "grid_search_best": "Sadece En İyi Model",
        "lbl_use_cv": "K-Fold Cross-Validation",
        "lbl_cv_folds": "K (Fold):",
        "msg_invalid_cv": "Lütfen geçerli bir K değeri girin (ör. 3, 5).",
        "lbl_export_code": "Python kodu export",
        "msg_code_exported": "✅ Python kodu dışa aktarıldı (exported_training.py)",
        "msg_code_export_failed": "⚠️ Kod export hatası: {error}",
        "btn_select_all": "Tümünü Seç",
        "btn_clear_all": "Tümünü Temizle",
        "lbl_augmentation": "📈 Veri Çoğaltma (Data Augmentation)",
        "lbl_profile": "Profil:",
        "lbl_multiplier": "Çarpan:",
        "msg_augmentation_start": "📈 Data Augmentation uygulanıyor ({profile}, {mult}x)...",
        "msg_augmentation_done": "✅ Veri seti {mult}x çoğaltıldı ({count} örnek)",
        "lbl_low_memory_mode": "Düşük Bellek Modu (Batch Processing)",
        "lbl_epoch": "Epoch:",
        "msg_folder_structure": "Klasör yapısı: root/sınıf_adı/dosya.uzantı",
        "msg_folder_structure_audio": "Klasör yapısı: root/sınıf_adı/ses_dosyası.wav",
        "msg_no_images": "Klasörde uygun görüntü bulunamadı!",
        "msg_no_audio": "Klasörde uygun ses dosyası bulunamadı!",
        "msg_no_models_batch": "Eğitilecek uygun model bulunamadı (Tümü Batch Mode desteklemiyor olabilir).",
        "msg_invalid_text_params": "Lütfen Max Features ve N-Gram için geçerli sayısal değerler girin.",

        "btn_select_csv_batch": "CSV Seç (Toplu Tahmin)",
        "btn_run_batch": "Toplu Tahmin",
        "msg_select_csv_first": "Lütfen önce bir CSV seçin.",
        "msg_missing_columns": "CSV dosyasında eksik sütunlar var: {cols}",
        "msg_saved_predictions": "Tahminler kaydedildi: {path}"
    },
    "en": {
        "app_title": "Training Interface",
        "sidebar_text": "Text Training",
        "sidebar_image": "Image Training",
        "sidebar_audio": "Audio Training",
        "sidebar_tabular": "Tabular Training",
        "sidebar_inference": "Inference",
        "tab_config": "⚙️ Configuration",
        "tab_results": "📊 Results",
        "btn_file_select": "📂 Select File",
        "btn_folder_select": "📂 Select Folder",
        "lbl_no_file": "No file selected",
        "lbl_no_folder": "No folder selected",
        "header_dataset": "📁 Dataset Selection",
        "header_models": "🤖 Model Selection",
        "header_params": "🎛️ Training Parameters",
        "lbl_test_size": "Test Data Ratio:",
        "btn_start_training": "🚀 Start Training",
        "btn_stop_training": "🛑 Stop Training",
        "btn_stopping": "🛑 Stopping...",
        "btn_training_running": "Training...",
        "btn_clear_results": "🗑️ Clear Results",
        "lbl_output_options": "📦 Output Options",
        "opt_save_models": "Model files",
        "opt_save_datasets": "Datasets",
        "opt_save_vectorizer": "Vectorizer",
        "opt_save_scaler": "Scaler",
        "opt_save_extra": "Extra files",
        "opt_save_plots": "Plots",
        "opt_save_comparison": "Comparison CSV",
        "opt_save_summary": "Summary reports (JSON/MD/HTML)",
        "opt_save_model_card": "Model card",
        "opt_save_onnx": "ONNX export",

        "help_stop_words": "Stop-words remove common low-information words (e.g., the, and). This can reduce noise and improve text classification. Choose Turkish/English in the Text Training screen.",
        "help_sparse_tfidf": "Sparse TF-IDF uses a sparse matrix to reduce memory usage for large text datasets. Enable it in the Text Training screen.",
        "help_low_memory_mode": "Low memory mode streams image files in batches to reduce RAM usage. Enable it in the Image Training screen.",
        "help_augmentation": "Data augmentation increases dataset size by applying transforms to images, improving generalization. Enable it in Image Training and choose profile and multiplier.",
        "help_kfold": "K-Fold Cross-Validation splits data into K folds and evaluates multiple runs for more reliable metrics. Enable and set K (e.g., 3 or 5).",
        "help_output_options": "Output options let you choose which files are saved. Disable unnecessary outputs to avoid large folders.",

        "model_info_naive_bayes": "Naive Bayes is fast and strong for text classification, assuming feature independence. Works well on high-dimensional text.",
        "model_info_nb_gaussian": "Gaussian Naive Bayes is suited for continuous numeric features. Simple and fast, works with small datasets.",
        "model_info_svm": "SVM finds the best separating hyperplane. Strong for high-dimensional data, good for small/medium datasets.",
        "model_info_random_forest": "Random Forest averages many decision trees. Robust to noise and a strong baseline model.",
        "model_info_log_reg": "Logistic Regression is a fast, interpretable linear classifier. Strong baseline for text/tabular data.",
        "model_info_decision_tree": "Decision Tree is interpretable and fast but can overfit. Depth tuning is important.",
        "model_info_decision_tree_entropy": "Decision Tree (Entropy) splits by information gain, an alternative to Gini.",
        "model_info_gradient_boosting": "Gradient Boosting is a powerful ensemble that corrects errors sequentially. Higher accuracy but slower.",
        "model_info_knn": "KNN predicts based on nearest neighbors. Simple but slow on large datasets.",
        "model_info_linear_regression": "Linear Regression models a linear relationship. Simple and fast regression method.",
        "model_info_ridge": "Ridge adds L2 regularization to linear regression, reducing overfitting and multicollinearity issues.",
        "model_info_lasso": "Lasso adds L1 regularization, which can zero out coefficients and perform feature selection.",
        "model_info_svr": "SVR is SVM-based regression. Strong on small/medium datasets with non-linear patterns.",
        "model_info_rf_regressor": "Random Forest Regressor is robust and flexible for regression tasks.",
        "model_info_gb_regressor": "Gradient Boosting Regressor often yields high accuracy but trains slower.",
        "model_info_dt_regressor": "Decision Tree Regressor is interpretable but can overfit without depth control.",
        "model_info_knn_regressor": "KNN Regressor predicts by averaging neighbors. Slow on large datasets.",
        "model_info_simple_cnn": "Simple CNN is a lightweight model for small image datasets.",
        "model_info_deep_cnn": "Deep CNN is more expressive for complex images but trains longer.",
        "chk_optimize": "Find Best Parameters (Grid Search)",
        "msg_training_started": "Training started...",
        "msg_training_complete": "All training completed!\nResults and datasets saved to '{save_dir}'.",
        "msg_error": "Error",
        "msg_warning": "Warning",
        "msg_select_file_first": "Please select a file first.",
        "msg_select_folder_first": "Please select the dataset folder first.",
        "msg_select_features": "You must select at least one feature column.",
        "msg_select_target": "You must select a target column.",
        "msg_select_model": "You must select at least one model.",
        "msg_file_read_error": "File could not be read: {error}",
        "msg_training_error": "Training error: {error}",
        "msg_model_load_error": "Model could not be loaded: {error}",
        "msg_file_load_error": "File could not be loaded: {error}",
        "msg_load_error": "Could not load: {error}",
        "msg_audio_load_error": "Audio load error: {error}",
        "msg_image_load_error": "Image load error: {error}",
        "msg_batch_predict_error": "Batch prediction error: {error}",
        "lbl_text_col": "Text Column:",
        "lbl_label_col": "Label Column:",
        "lbl_max_features": "Max Features:",
        "lbl_ngram": "N-Gram (e.g. 1,1):",
        "lbl_stop_words": "Stop-words:",
        "stop_words_none": "None",
        "stop_words_tr": "Turkish",
        "stop_words_en": "English",
        "lbl_sparse_tfidf": "Sparse TF-IDF (Low RAM)",
        "info_folder_structure": "ℹ️ There must be a separate subfolder for each class inside the folder.",
        "lbl_columns": "Column Settings",
        "col_feature": "Feature (Input)",
        "col_name": "Column Name",
        "col_text": "Text Column",
        "col_target": "Target (Output)",
        "val_int_or_none": "(number or 'None')",
        "btn_save": "Save",
        "win_settings_title": "Settings",
        "lbl_params": "Parameters",
        "lbl_model_info_title": "{model} - Model Info",
        "lbl_accuracy": "Accuracy",
        "lbl_precision": "Precision",
        "lbl_recall": "Recall",
        "lbl_f1": "F1 Score",
        "lbl_r2": "R2",
        "lbl_mse": "MSE",
        "lbl_mae": "MAE",
        "lbl_model_comparison": "🏆 Overall Comparison",
        "lbl_best_model": "BEST MODEL",
        "lbl_model": "Model",
        "lbl_file": "File",
        "lang_toggle": "TR",
        "loading_data": "⏳ Loading data...",
        "loading_images": "📂 Loading images...",
        "loading_audio": "🎵 Processing audio files...",
        "err_no_images": "No suitable images found in the folder!",
        "err_no_audio": "No suitable audio files found in the folder!",
        "col_select_first": "Select File First",

        # Inference Tab
        "header_load": "📂 Load Model & Data",
        "lbl_model_type": "Model Type:",
        "type_text": "Text",
        "type_image": "Image",
        "type_audio": "Audio",
        "type_tabular": "Tabular",
        "btn_select_model": "Select Model File (.joblib)",
        "btn_load_vectorizer": "Load Vectorizer",
        "btn_load_scaler": "Load Scaler",
        "btn_load_extra": "Other Files",
        "lbl_not_loaded": "Not loaded",
        "lbl_not_needed": "Not needed",
        "lbl_loaded_auto": " (Auto)",
        "lbl_scaler_optional": "Scaler (if any)",
        "btn_load_features": "Column Info (feature_cols)",
        "btn_load_label_enc": "Label Encoder",
        "btn_load_encoder": "Preprocessor (encoder)",
        "header_predict": "🔮 Predict",
        "lbl_input_file": "No file selected",
        "lbl_tabular_input": "Data Input",
        "btn_predict": "PREDICT",
        "lbl_result_wait": "Waiting for result...",
        "lbl_result": "Result: {result}",
        "lbl_confidence": " (Confidence: %{value})",
        "msg_model_loaded": "Model and auxiliary files loaded.",
        "msg_file_loaded": "File loaded.",
        "msg_enter_text": "Please enter text.",
        "msg_load_vectorizer": "You must load a Vectorizer for text models.",
        "msg_select_image": "Please select an image file.",
        "msg_select_audio": "Please select an audio file.",
        "msg_load_features": "Please load column info (feature_cols).",
        "msg_load_model_first": "Please load a model first.",
        "msg_encoding_error": "Encoding error: {error}\nYour inputs may not match categories seen during training.",

        # Parameter Descriptions
        "desc_alpha": "Smoothing parameter (0.0 - 1.0+)",
        "desc_var_smoothing": "Portion of variance for calculation stability",
        "desc_C": "Regularization parameter (Low=Simpler, High=More Complex)",
        "desc_kernel": "Shape of the decision boundary",
        "desc_n_estimators": "Number of trees to build",
        "desc_max_depth": "Maximum depth of the tree (None=Unlimited)",
        "desc_min_samples_split": "Min samples required to split a node",
        "desc_max_iter": "Maximum number of iterations",
        "desc_learning_rate": "Rate to shrink contribution of each tree (0.0-1.0)",
        "desc_n_neighbors": "Number of neighbors (k)",
        "desc_weights": "Weighting (uniform=Equal, distance=By Distance)",
        
        # New translations
        "lbl_task_type": "Task Type:",
        "task_classification": "Classification",
        "task_regression": "Regression (Prediction)",
        "lbl_grid_search_scope": "Grid Search Scope:",
        "grid_search_all": "All Models",
        "grid_search_best": "Best Model Only",
        "lbl_use_cv": "K-Fold Cross-Validation",
        "lbl_cv_folds": "K (Fold):",
        "msg_invalid_cv": "Please enter a valid K value (e.g. 3, 5).",
        "lbl_export_code": "Export Python code",
        "msg_code_exported": "✅ Python code exported (exported_training.py)",
        "msg_code_export_failed": "⚠️ Code export error: {error}",
        "btn_select_all": "Select All",
        "btn_clear_all": "Clear All",
        "lbl_augmentation": "📈 Data Augmentation",
        "lbl_profile": "Profile:",
        "lbl_multiplier": "Multiplier:",
        "msg_augmentation_start": "📈 Applying data augmentation ({profile}, {mult}x)...",
        "msg_augmentation_done": "✅ Dataset augmented {mult}x ({count} samples)",
        "lbl_low_memory_mode": "Low Memory Mode (Batch Processing)",
        "lbl_epoch": "Epoch:",
        "msg_folder_structure": "Folder structure: root/class_name/file.ext",
        "msg_folder_structure_audio": "Folder structure: root/class_name/audio_file.wav",
        "msg_no_images": "No suitable images found in the folder!",
        "msg_no_audio": "No suitable audio files found in the folder!",
        "msg_no_models_batch": "No suitable models found for training (All may not support Batch Mode).",
        "msg_invalid_text_params": "Please enter valid numeric values for Max Features and N-Gram.",

        "btn_select_csv_batch": "Select CSV (Batch Predict)",
        "btn_run_batch": "Run Batch Predict",
        "msg_select_csv_first": "Please select a CSV first.",
        "msg_missing_columns": "Missing columns in CSV: {cols}",
        "msg_saved_predictions": "Predictions saved: {path}"
    }
}

def get_text(key, lang="tr"):
    return TEXTS.get(lang, TEXTS["tr"]).get(key, key)
